[package]
name = "encode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "2.1.0"
clap = "4.5.16"
html-escape = "0.2.9"
base64 = "0.22.1"
hex = "0.4.3"